### ISSUE TITLE
Interval range?

### ISSUE THREAD

**Issue by Z1839** [lovac42/ReMemorizeButtons#3]
Hey man, i'm a really big fan of your work.

Just a question: I was wondering if for Rememorizer buttons I could use an interval range (eg, 3-5 days) rather than just one day.

**Comment by lovac42** [comment]
The fuzz would be handled by the scheduler on V1, I'll add that in for V2. And you can use DeFuzz to control the fuzzing. 3d is 2-4, 4d would be 3-4, and 5d is 4-6.

**Comment by Z1839** [comment]
Thank you. I forgot to mention i'm using the V2 scheduler. So you're saying that without using DeFuzz, the addon will automatically add some fuzz to the rememorizer buttons I select?

**Comment by lovac42** [comment]
In the current version, for modifier buttons, it does so for V1, but not V2. That needs to be fixed.

ReMemorize buttons, which sends a signal to ReMemorize, depends on your settings. If you have fuzz turned on in the config for ReMemorize, then it will fuzz the interval.

The term RM buttons and Mod buttons maybe confusing, but the idea came to me much later. They are logged differently, you can read the readme for more details.

**Comment by Z1839** [comment]
Much appreciated my man.
