### ISSUE TITLE
Color changes for extra buttons

### ISSUE THREAD

**Issue by Z1839** [lovac42/ReMemorizeButtons#4]
Hey my man,

I was wondering if you could help me change the colors on the ReMemorize buttons.
First off, I read your guide and saw I needed to download the addon "Large and Colorful buttons". However, I quite frankly don't like the size and style of the buttons, so I was wondering if there was a way to only use the addon on the extra Rememorize buttons.

I saw the code in your tutorial, but I was wondering if I just copy and paste it into the text editor for the actual rememorize button config, or just for the Large colorful addon.

Another note: one addon I do enjoy is "Button colors"  https://ankiweb.net/shared/info/2494384865

Perhaps there would be a way to use this addon on the extra ReMemorize buttons?

**Comment by lovac42** [comment]
Sorry man this is a huge lesson on CSS I can't get involved in. For that addon "Large and Colorful buttons", there is a css file in user_files folder, you just edit it and play around with the styles. Google for css tutorials. or just copy and paste from the readme. .rem_time1 for the 5th button, .rem_time2 for the 2nd button and so on, add numbers as necessary.
