### ISSUE TITLE
Not able to add buttons after new update?

### ISSUE THREAD

**Issue by Z1839** [lovac42/ReMemorizeButtons#5]
Hey man, I installed the new update that has 2.1 fuzz, and it seems that my new buttons aren't showing up. My changes are still showing up in the config, but nothing seems to be showing up.

Any idea my friend?

**Comment by lovac42** [comment]
That's odd, I didn't change much here. Which version were you updating from?
Try clicking on restore default config.

It's possible you downloaded the wrong version, beta instead of beta4:
https://github.com/lovac42/ReMemorizeButtons/releases/download/v0.1.7/rememorize_btn_21.ankiaddon

**Comment by Z1839** [comment]
Ah yes, I downloaded the wrong version. Thank you.

**Comment by lovac42** [comment]
np
