### ISSUE TITLE
Changing button layout

### ISSUE THREAD

**Issue by Z1839** [lovac42/ReMemorizeButtons#6]
Hey man, sorry for all the issue posts. I'm not sure how to contact you directly. I appreciate all your help.

I was wondering how you can get the buttons to stack up vertically like shown in the photo: https://raw.githubusercontent.com/lovac42/ReMemorizeButtons/master/screenshots/donts.png

Thank you!

**Comment by lovac42** [comment]
photoshop, but you can do it with css. I'm not a graphic design, so can't you help there.
